spring.application.name=ms-banque
# H2 in memory
spring.datasource.url=jdbc:h2:mem:banque;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Port & base-path Spring Data REST
server.port=8082
spring.data.rest.base-path=/api
spring.data.rest.detection-strategy=annotated

# Enable SQL logs
spring.jpa.show-sql=true

# Disable Spring Boot DevTools automatic restart
spring.devtools.restart.enabled=false
